# -*- coding: utf-8 -*-
"""Estrutura_decisao_if

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cr1n3W8GhIubNRfQDiPrO7yoqSZ3t9Rx
"""

#exercício_1
n1 = float(input('Dígite o primeiro número: '))
n2 = float(input('Digite o segundo número: '))
if n1 + n2 > 15:
  print(n1 + n2)
else:
  print(f'A soma dos números {n1} e {n2} é menor que 15.')

#exercício_2
n = int(input('Dígite um número: '))
if n < 0:
  print('Número negativo.')
elif n > 0:
  print('Número positivo')
else:
  print('Número neutro.')

#exercício_3
i = int(input('Dígite a idade: '))
if i >= 18:
  print(f'{i} anos -> Maior de idade.')
else:
  print(f'{i} anos -> Menor de idade.')

#exercício_4
t = float(input('Digíte a temperatura: '))
if t > 25:
  print(f'Temperatura de {t}º é quente.')
elif t < 25 and t > 18:
  print(f'Temperatura de {t}º é agradável.')
else:
  print(f'Temperarura de {t}º é frio.')

#exercício_5
n1 = int(input('Digíte o primeiro número: '))
n2 = int(input('Digíte o segundo número: '))
if n1 != n2:
  print(f'{n1} é diferente de {n2}.')
else:
  print(f'{n1} é igual a {n2}.')

#exercício_6
password = int(input('Digíte a senha: '))
if password == 1234:
  print('ACESSO PERMITIDO.')
else:
  print('SENHA INVÁLIDA. ACESSO NEGADO!')

#exercício_7
notaA = float(input('Digíte a primeira nota: '))
notaB = float(input('Digíte a segunda nota: '))
mediaAB = ((notaA + notaB)/2)
if mediaAB >= 7:
  print(f'Nota {mediaAB}: Aluno APROVADO!')
elif mediaAB >= 5 and mediaAB <7:
  print(f'Nota {mediaAB}: Aluno EM EXAME!')
else:
  print(f'Nota {mediaAB}: Aluno REPROVADO!')

#exercicio_8
goltimeM = int(input('Gols do time Mandante: '))
goltimeV = int(input('Gols do time Visitante: '))
if goltimeM == goltimeV:
  print(f'O jogo EMPATOU.')
elif goltimeM > goltimeV:
  print(f'O time Mandante GANHOU!')
else:
  print(f'O time Visitante GANHOU')

#exercicio_9
horotimo = ''
while horotimo == '':
  horotimo = str(input('Digíte o turno letivo: M -> Matutino, V -> Vespertino ou N ->Noturno ')).upper()
  if horotimo == 'M':
    print('Bom dia!')
  elif horotimo == 'V':
    print('Boa tarde!')
  elif horotimo == 'N':
    print('Boa noite!')
  else:
    horotimo = ''
    str(print(f'OPÇÃO INVÁLIDA! Digite o turno letivo: M, V ou N. ')).upper()

#exercio_10
i = 0
while i == 0:
  i = int(input('Insira sua idade: '))
  if i <= 11 and i > 0:
    print('Categoria infantil.')
  elif i <= 18 and i > 0:
    print('Categoria adolescente.')
  elif i <= 24 and i > 0:
    print('Categoria jovem.')
  elif i <= 40 and i > 0:
    print('Categoria adulta.')
  elif i <= 60 and i >0:
    print('Categoria meia idade.')
  elif i <=110 and i >0:
    print('Categoria idosa.')
  else:
    i = 0
    print('Input inválido, insira um número inteiro positivo compreendindo no intervalo [1, 110]')

#exercicio_11
money = float(input('Salário R$: '))
if money <= 280.00 and money >0:
  newmoney = (money + (money * 0.2))
  print(f'O salário atual é de R${money:.2f}. Aumento de 20% concedido. O aumento foi de R${newmoney - money} e o salário atualizado é R${newmoney:.2f} unidades monetárias (u.m).')
elif money <= 700.00 and money > 0:
  newmoney = (money + (money * 0.15))
  print(f'O salário atual é de R${money:.2f}. Aumento de 15% concedido. O aumento foi de {newmoney - money} e o salário atualizado é R${newmoney:.2f} unidades monetarias (u.m).')
elif money <= 1500.00 and money > 0:
  newmoney = (money + (money * 0.10))
  print(f'O salário atual é de R${money:.2f}. Aumento de 10% concedido. O aumento foi de {newmoney - money} e o salário atualizado é R${newmoney:.2f} unidades monetarias (u.m).')
elif money > 1500.00:
  newmoney = (money + (money * 0.05))
  print(f'O salário atual é de R$ {money:.2f}. Aumento de 5% concedido. O aumento foi de {newmoney - money} e o salário atualizado é R${newmoney:.2f} unidades monetarias (u.m).')

#exercicio_12
day = 0
while day == 0:
  day = int(input('Digite númericamente o dia da semana, tendo em vista que a semana contém 7 dias e o primeiro dia da semana é domingo: '))
  if day == 1:
    print('Domingueira.')
  elif day == 2:
    print('Segunda-feira.')
  elif day == 3:
    print('Terça-feira.')
  elif day == 4:
    print('Quarta-feira.')
  elif day == 5:
    print('Quint-feira')
  elif day == 6:
    print('Sexta-feira')
  elif day == 7:
    print('Sabádo')
  else:
    day =  0
    print('Entrada inválida!')

#exercicio_13
c = float(input('Informe a temperatura em Cº: '))
f = float((c * 1.8) + 32 )
print(f'A temperatura de {c}º convertida para Fahrenheit é {f}')

#exercício_14
idade = 0
while idade == 0:
  idade = int(input('Digíte sua idade: '))
  if idade < 16 and idade > 0:
    print('Voto proíbido.')
    idade = 0
  elif idade < 18 and idade >= 16:
    print('Voto facultativo.')
    idade = 0
  elif idade >= 18 and idade < 65:
    print('Voto obrigatório.')
    idade = 0
  elif idade >= 65:
    print('Voto facultativo.')
    idade = 0

#exercício_15_e_16
print('Responda às seguintes perguntas com sim ou não: ')
pergunta1 = input('Telefonou para a vitima: ').lower()
pergunta2 = input('Esteve no local do crime: ').lower()
pergunta3 = input('Mora perto da vítima: ').lower()
pergunta4 = input('Devia para a vítima: ').lower()
pergunta5 = input('Já trabalhou com a vítima: ').lower()

positivas = 0

if pergunta1 == 'sim':
  positivas += 1
elif pergunta2 == 'sim':
  positivas += 1
elif pergunta3 == 'sim':
  positivas += 1
elif pergunta4 == 'sim':
  positivas += 1
elif pergunta5 == 'sim':
  positivas += 1

if positivas == 2:
  print('Suspeita')
elif positivas <=3 and positivas <=4:
  print('Cúmplice')
elif positivas == 5:
  print('Culpado!')
else:
  print('Inocente')

#exercício_17

produtoA = float(input('Qual o preço do arroz do tipo A? R$'))
produtoB = float(input('Qual o preço do arroz do tipo B? R$'))
produtoC = float(input('Qual o preço do arroz do tipo C? R$'))
7if produtoA < produtoB and produtoA < produtoC:
  print('Comprar arroz do tipo A.')
elif produtoB < produtoA and produtoB < produtoC:
  print('Comprar arroz do tipo B.')
elif produtoC < produtoA and produtoC < produtoB:
  print('Comprar arroz do tipo C.')

#pseudocode_for
Programa Looping_Para
var
   x,r, cont: inteiro
Início
  para cont de 1 a 4
    leia (x)
    r <- x * 12
    escreva(r)
  fim_para
fimm

#exercicio_18
i = 0
for i in range(0, 5):
  i = int(input('Digíte um número: '))
  r = i * 3
  print(f'O valor de R é {r}.')